baseURL = "/"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

defaultContentLanguage = "en"

# The name of this wonderful theme ;-).
theme = "hugo-scroll"

# The browser tab name
title = "YGO SFV"

# In order to add version information in the page's footer set to true.
# enableGitInfo = true

# Theme-specific variables `.Site.Params.myParamName`
[params]

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/yugioh.ico"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and https://gohugo.io/templates/internal#open-graph.
    # NOT the actual header background image, go to _index.md instead
    images = ["images/cover-image.jpg"]

    # When set true, it creates a visual guard (partially transparent rounded box), preventing non-ideal background images from interfering with title/description headings
    # Ideal images are homogenous around the centre and contrasting to the text.
    # see CSS classes: .title-and-description-guard, .blog-title, .blog-description
    # see _index.md header_headline and header_subheadline
    title_guard = false

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "AHLayer8Tech presents YGO SFV - Tracking Yugioh Tournaments and Locals in and around the San Fernando Valley"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "A website for tracking Yugioh trading card game local tournaments and events in and around the San Fernando Valley."

    # Show a menu of languages available
    language_menu = true

    # Show also a language menu item for the current language, if false only
    # show the remaining languages
    show_current_lang = true

    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Plain HTML is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© AHLayer8Tech"

    # This theme will, by default, inject a design-by-line at the bottom of the page.
    # You can turn it off, but we would really appreciate if you don’t :-)
    hidedesignbyline = false

    # The sections of the home page alternate styling. Mark invert as true to swap the styling of the sections
    invertSectionColors = false
    
    [params.footer]
    # Show contact icons for email/phone (if specified) in the footer of the page
    showContactIcons = false

    # Show links indicated with footer_menu and footer_menu_title in the footer of the page
    showFooterLinks = false

    [params.meta]
        keywords = "yugioh, yu-gi-oh!, ygo, yu-gi-oh! trading card game, yu-gi-oh! tcg, yugioh tcg, yugiohtcg, tcg, trading card game, ots, official tournament store, lgs, local game store, cardshop, locals, events, tournaments, regionals, case tournaments, san fernando valley, sfv, los anageles, la, southern california, socal, play yugioh, play yu-gi-oh!"

    [[params.contacts]]
        label = "email"
        value = "ahlayer8tech.vcaco[at]aleeas.com"
        url = "mailto:ahlayer8tech.vcaco[at]aleeas.com"
        icon = "fa fa-envelope"

    # Add additional contacts here!
    # [[params.contacts]]
    #     label = ""
    #     value = ""
    #     url = ""
    #     icon = ""
